services:
  - type: web
    name: stock-price-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/app/app.py
    envVars:
      - key: PORT
        value: 10000  # Render will override this automatically
